import fs from 'fs';

const venuesPath = './public/data/venues.json';
const pricesPath = './public/data/prices.json';

const venues = JSON.parse(fs.readFileSync(venuesPath, 'utf8'));
const prices = JSON.parse(fs.readFileSync(pricesPath, 'utf8'));

const newVenues = [
  {
    "id": "pz-181",
    "name": "Rosticceria Bar Liana",
    "address": "Via delle Rose, 57, 80063 Piano di Sorrento NA",
    "cityId": "piano",
    "phone": "+39 081 878 8220",
    "category": "traditional",
    "rating": 4.6,
    "description": "Historic rotisserie and pizzeria. Famous for its 'panuozzi', pizzas, and a wide variety of handmade fried snacks like potato croquettes.",
    "descriptionIt": "Storica rosticceria e pizzeria. Celebre per i suoi panuozzi, pizze e l'ampia scelta di fritti artigianali come i crocchè di patate.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g616172-d13205546-Reviews-Rosticceria_Bar_Liana-Piano_di_Sorrento_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rosticceria+Bar+Liana+Piano+di+Sorrento",
    "margheritaPrice": 5.5,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "official-menu",
    "cityName": "Piano di Sorrento",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-182",
    "name": "Pizzeria Da Franco",
    "address": "Corso Filangieri, 96, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 801 6245",
    "category": "traditional",
    "rating": 4.5,
    "description": "Historic pizzeria and rotisserie beloved by residents for its authenticity and reasonable prices.",
    "descriptionIt": "Storica pizzeria e rosticceria molto amata dai residenti per l'autenticità e i prezzi contenuti.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1537280-Reviews-Pizzeria_da_Franco-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Da+Franco+Vico+Equense",
    "margheritaPrice": 6.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-183",
    "name": "Pizzeria Al Buco",
    "address": "Via Roma, 19, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 801 6075",
    "category": "traditional",
    "rating": 4.4,
    "description": "Famous for generous portions and the typical 'Turkish pizza'.",
    "descriptionIt": "Celebre per le porzioni generose e la tipica 'pizza turca'.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1100344-Reviews-Pizzeria_Al_Buco-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Al+Buco+Vico+Equense",
    "margheritaPrice": 6.5,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-184",
    "name": "Pizzeria Tiziano",
    "address": "Corso Filangieri, 132, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 879 8138",
    "category": "traditional",
    "rating": 4.3,
    "description": "Very popular spot in the center of Vico, known for its light dough and great value.",
    "descriptionIt": "Locale molto popolare nel centro di Vico, noto per l'impasto leggero e l'ottimo rapporto qualità-prezzo.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1597942-Reviews-Pizzeria_Tiziano-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Tiziano+Vico+Equense",
    "margheritaPrice": 7.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-185",
    "name": "Cremeria Gabriele",
    "address": "Corso Umberto I, 7, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 879 8744",
    "category": "traditional",
    "rating": 4.8,
    "description": "World-famous for its ice cream, it also offers excellent traditional pizza in a historic setting.",
    "descriptionIt": "Famosa in tutto il mondo per il gelato, offre anche un'ottima pizza tradizionale in un contesto storico.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1544383-Reviews-Cremeria_Gabriele-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cremeria+Gabriele+Vico+Equense",
    "margheritaPrice": 8.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-186",
    "name": "Terramia",
    "address": "Via Roma, 42, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 879 8830",
    "category": "gourmet",
    "rating": 4.6,
    "description": "Elegant restaurant and pizzeria focusing on high-quality local ingredients.",
    "descriptionIt": "Elegante ristorante e pizzeria focalizzato su ingredienti locali di alta qualità.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d2325380-Reviews-Terramia-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Terramia+Vico+Equense",
    "margheritaPrice": 9.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-187",
    "name": "Ma Che Bontà",
    "address": "Corso Filangieri, 102, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 879 8064",
    "category": "traditional",
    "rating": 4.4,
    "description": "Known for its 'pizza a metro' and variety of toppings in a friendly environment.",
    "descriptionIt": "Nota per la sua pizza a metro e la varietà di condimenti in un ambiente amichevole.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d3527264-Reviews-Ma_Che_Bonta-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ma+Che+Bonta+Vico+Equense",
    "margheritaPrice": 7.5,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-188",
    "name": "Pizzeria Cardillo",
    "address": "Via Fornacelle, 10, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 802 8585",
    "category": "traditional",
    "rating": 4.5,
    "description": "A local gem in the Fornacelle area, famous for its light dough and panoramic views.",
    "descriptionIt": "Una gemma locale nella zona di Fornacelle, famosa per l'impasto leggero e la vista panoramica.",
    "status": "open",
    "frazione": "Fornacelle",
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1597942-Reviews-Pizzeria_Cardillo-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Cardillo+Vico+Equense",
    "margheritaPrice": 6.5,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-189",
    "name": "O' Sole Mio",
    "address": "Via Seiano, 17, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 802 8130",
    "category": "traditional",
    "rating": 4.3,
    "description": "Traditional flavors in a panoramic spot in Seiano.",
    "descriptionIt": "Sapori tradizionali in un punto panoramico a Seiano.",
    "status": "open",
    "frazione": "Seiano",
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1597942-Reviews-O_Sole_Mio-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=O+Sole+Mio+Vico+Equense",
    "margheritaPrice": 7.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  },
  {
    "id": "pz-190",
    "name": "Antica Pizzeria da Michele (Vico Equense)",
    "address": "Via Domenico Veniero, 1, 80069 Vico Equense NA",
    "cityId": "vico-equense",
    "phone": "+39 081 879 8456",
    "category": "traditional",
    "rating": 4.6,
    "description": "The world-renowned brand with a beautiful branch in Vico Equense.",
    "descriptionIt": "Il marchio famoso in tutto il mondo con una bellissima sede a Vico Equense.",
    "status": "open",
    "frazione": null,
    "imageUrl": null,
    "tripadvisor": "https://www.tripadvisor.it/Restaurant_Review-g194947-d1537280-Reviews-Antica_Pizzeria_da_Michele-Vico_Equense_Province_of_Naples_Campania.html",
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Antica+Pizzeria+da+Michele+Vico+Equense",
    "margheritaPrice": 8.0,
    "lastUpdated": new Date().toISOString(),
    "priceSource": "estimated",
    "cityName": "Vico Equense",
    "cityRegion": "Penisola Sorrentina"
  }
];

venues.push(...newVenues);

newVenues.forEach(v => {
  prices.push({
    "pizzeriaId": v.id,
    "margheritaPrice": v.margheritaPrice,
    "lastUpdated": v.lastUpdated,
    "source": v.priceSource,
    "history": [
      {
        "date": v.lastUpdated,
        "price": v.margheritaPrice
      }
    ]
  });
});

fs.writeFileSync(venuesPath, JSON.stringify(venues, null, 2));
fs.writeFileSync(pricesPath, JSON.stringify(prices, null, 2));
console.log(`Added ${newVenues.length} new pizzerias (Bar Liana + Vico Equense).`);
